update legacy terms to chrysalis
lucas-tortora/blueprints pull request #1
Opened 2021-11-15 14:31 UTC by karimkozman

2021-11-15 14:41 UTC, karimkozman commented
Screenshots in ipfs-docs-c2-migration.md are still to be updated (public node at https://ipfs.io doesn’t appear to want to retrieve the file - awaiting  DevOps to restart https://ipfs.iota.cafe/ as it might fix it to be able to take a screenshot of the last step).  

Diagrams in architecture.md need to be updated ("transaction hash" to "message ID")
![data-storage-retrieve](https://user-images.githubusercontent.com/25418520/141800618-dc7d4532-c742-4cee-8acc-dec4795b11f2.png)
![data-storage-store](https://user-images.githubusercontent.com/25418520/141800630-213ea122-c6bc-4faa-9a73-a723c6c58056.png)

2021-11-15 17:33 UTC, lucas-tortora requested changes
Great work :) !! Just some small changes.  Please let me know if you have any doubts/issues with these.

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/architecture.md
> +![Data Storage PoC - IOTA/IPFS - Architecture](../static/img/blueprints/data-storage-ipfs.png)
I know it's a bit of a pain as you can't see images outside the docusaurus build, but as the repo will be imported by the wiki when building, we need to use absolute image paths for static assets. 
```suggestion
![Data Storage PoC - IOTA/IPFS - Architecture](/img/blueprints/data-storage-ipfs.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/architecture.md
> +![Data Storage PoC - IOTA/IPFS - Store File](../static/img/blueprints/data-storage-store.png)
I know it's a bit of a pain as you can't see images outside the docusaurus build, but as the repo will be imported by the wiki when building, we need to use absolute image paths for static assets.

```suggestion
![Data Storage PoC - IOTA/IPFS - Store File](/img/blueprints/data-storage-store.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/deployment-and-testing.md
> +![Upload File for IOTA IPFS Data Storage PoC](../static/img/blueprints/data-storage-upload.png)
```suggestion
![Upload File for IOTA IPFS Data Storage PoC](/img/blueprints/data-storage-upload.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/deployment-and-testing.md
> +    ![Upload File for IOTA IPFS Data Storage PoC - Populated](../static/img/blueprints/data-storage-upload2.png)
```suggestion
![Upload File for IOTA IPFS Data Storage PoC - Populated](/img/blueprints/data-storage-upload2.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/deployment-and-testing.md
> +    ![Uploaded File for IOTA IPFS Data Storage PoC](../static/img/blueprints/data-storage-upload-finished.png)
```suggestion    
![Uploaded File for IOTA IPFS Data Storage PoC](/img/blueprints/data-storage-upload-finished.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/deployment-and-testing.md
> +    ![Retrieve File for IOTA IPFS Data Storage PoC](../static/img/blueprints/data-storage-upload-retrieve.png)
```suggestion
    ![Retrieve File for IOTA IPFS Data Storage PoC](/img/blueprints/data-storage-upload-retrieve.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/deployment-and-testing.md
> +    ![Retrieve File for IOTA IPFS Data Storage PoC](../static/img/blueprints/data-storage-upload-validated.png)
```suggestion
    ![Retrieve File for IOTA IPFS Data Storage PoC](/img/blueprints/data-storage-upload-validated.png)
```

2021-11-15 17:33 UTC, lucas-tortora commented on tangle-data-storage/deployment-and-testing.md
> +Try [running your own node](https://chrysalis.docs.iota.org/node_software) and configuring the application to connect to it.
We're in the process of redirecting everything to the wiki.
```suggestion
[Run your own node](https://wiki.iota.org/chrysalis-docs/node_software) and configure the application to connect to it.
```

2021-11-16 13:55 UTC, karimkozman commented
Screenshots update remaining

2021-11-23 14:36 UTC, lucas-tortora approved these changes
LGTME! Thanks for the updates :)

2021-11-23 14:36 UTC, merged